<?php

namespace api\controllers;

use api\models\Countries;
use yii\rest\ActiveController;
use app\helpers\BehaviorsFromParamsHelper;
use api\models\Profile;
use api\models\SignupForm;
use api\models\Bookings;
use api\models\Driver;
use api\models\Pass;
use api\models\Passenger;
use api\models\PhoneNumber;
use api\models\Rider;
use Codeception\Lib\Console\Message;
use common\models\LoginForm;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;
use common\models\User;
use yii;


class ApiController extends ActiveController
{

    public $enableCsrfValidation = false;

    /**
     * @param $action
     * @return bool
     * @throws yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        parent::beforeAction($action);

        return true;
    }

    public static function allowedDomains()
    {
        return [
            '*',                        // star allows all domains
        ];
    }

    // public function behaviors()
    // {
    //     $behaviors = parent::behaviors();
    //     $behaviors['authenticator'] = [
    //         'class' => CompositeAuth::className(),
    //         'authMethods' => [
    //             HttpBasicAuth::className(),
    //             HttpBearerAuth::className(),
    //             QueryParamAuth::className(),
    //         ],
    //     ];
    //     $behaviors['corsFilter'] = [
    //         'class' => \yii\filters\Cors::className(),
    //     ];
    //     return $behaviors;
    // }

    public $modelClass = 'common\models\User';


    public function actions()
    {
        $action = parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
    }

    public function actionTest()
    {
        return "Success";
    }

    public function actionCountries()
    {
        $countries = Countries::find()->asArray()->all();

        return ["countries" => $countries];
    }

    public function actionProfile()
    {

        $postdata = file_get_contents("php://input");
        $data = json_decode($postdata, true);

        $model = new Profile();

        $data = ['Profile' => [
            'name' => $data['name'],
            'countryId' => $data['countryId'],
            'phoneNumber' => $data['phoneNumber'],
            'lastname' => $data['lastname']
        ]];


        if ($model->load($data) &&  $model->save()) {
            return $model;
        }
        return $model;
    }

    //register user
    public function actionRegister()
    {

        $postdata = file_get_contents("php://input");
        $data = json_decode($postdata, true);

        $model = new SignupForm();

        $data = ['SignupForm' => [
            'username' => $data['username'], 'password' => $data['password'],
            'email' => $data['email']
        ]];

        if ($model->load($data) &&  $model->signup()) {
            return $model->hasErrors();
        }
        return $model->hasErrors();
    }


    //user can log in
    public function actionLogin()
    {

        $postdata = file_get_contents("php://input");
        $data = json_decode($postdata, true);

        $model = new LoginForm();

        $data = ['LoginForm' => [
            'username' => $data['username'], 'password' => $data['password'],
        ]];

        if ($model->load($data) &&  $model->login()) {
            $userData = User::find()->where(['username' => $model->username])->asArray()->one();
            return $userData;
        }
        return $model->hasErrors();
    }



    //Booking
    public function actionBookings()
    {

        $postdata = file_get_contents("php://input");
        $data = json_decode($postdata, true);

        $model = new Bookings();

        $data = ['Bookings' => [
            'passengerId' => $data['passengerId'],
            'status' => $data['status'],
            'bookingId' => $data['bookingId'],
            'amount' => $data['amount'],
            'riderId' => $data['riderId'],
            'date' => $data['date']
        ]];
        // var_dump($data);


        if ($model->load($data) &&  $model->save()) {
            return $model;
        }
        return $model;
    }


    //Driver place a ride
    public function actionDriverbook()
    {

        $postdata = file_get_contents("php://input");
        $data = json_decode($postdata, true);

        $model = new Driver();
        $data = ['Driver' => [
            'userId' => $data['userId'],
            // 'carId' => $data['carId'],
            'riderId' => $data['riderId'],
            'pickupLocation' => $data['pickupLocation'],
            'date' => $data['date'],
            'destination' => $data['destination']
        ]];


        if ($model->load($data) &&  $model->save()) {
            $userData = Pass::find()->where(['userId' => $model->userId])->asArray()->one();
            return $userData;
        }
        return $model;
    }


    //passenger looking for a ride
    public function actionPassengerplace()
    {

        $postdata = file_get_contents("php://input");
        $data = json_decode($postdata, true);

        $model = new Passenger();

        $data = ['Passenger' => [
            'userId' => $data['userId'],
            'pickupLocation' => $data['pickupLocation'],
            'date' => $data['date'],
            'destination' => $data['destination']
        ]];


        if ($model->load($data) &&  $model->save()) {
            $userData = Pass::find()->where(['userId' => $model->userId])->asArray()->one();
            return $userData;
        }
        return $model;
    }


    //passenger enter phone number
    public function actionRider()
    {

        $postdata = file_get_contents("php://input");
        $data = json_decode($postdata, true);

        $model = new Rider();

        $data = ['Rider' => [
            'userId' => $data['userId'],
            'riderId' => $data['riderId'],
            'phoneNumber' => $data['phoneNumber']
        ]];


        if ($model->load($data) &&  $model->save()) {
            // $userData = Pass::find()->where(['userId' => $model->userId])->asArray()->all();
            return $model;
        }
        return $model;
    }

    //phone number to log in
    public function actionPhone()
    {
        $postdata = file_get_contents("php://input");
        $data = json_decode($postdata, true);
        $phone = Rider::find()->asArray()->one();
        return $phone;
    }


    //retrive all drivers available with same destination as passenger
    public function actionAvailable()
    {
        $postdata = file_get_contents("php://input");
        $data = json_decode($postdata, true);
        $phone = Driver::find()->asArray()->all();
        return $phone;
    }
    // // return Tags::find()
    // // ->joinWith(['news', 'news.categories C'])
    // // ->where(['C.id' => $this->id])
    // // ->distinct();





    // public function actionPhone()
    // {

    //     $postdata = file_get_contents("php://input");
    //     $data = json_decode($postdata, true);

    //     $model = new PhoneNumber();

    //     var_dump($data);
    //     $data = ['PhoneNumber' => [
    //         'phoneNumber' => $data['phoneNumber']
    //     ]];


    //     if ($model->load($data) &&  $model->save()) {
    //         return $model;
    //     }
    //     return $model;
    // }

    // public function actionPhone()
    // {
    //     $postdata = file_get_contents("php://input");
    //     $data = json_decode($postdata, true);
    //     $phone = Rider::find()->asArray()->all();
    //     if ($phone == []) {
    //         return [
    //             $phone,
    //             // log(1)
    //         ];
    //     }
    // }



    public function actionDriverlist()
    {
        $postdata = file_get_contents("php://input");
        $data = json_decode($postdata, true);
        $driver = Driver::find()->asArray()->all();
        return [
            'driver' => $driver,
        ];
    }



    //     public function actionAddtocart($productid,$userid,$quantity)
    //     {
    //         $checkcart = Productcart::find()->where(['userId'=>$userid])->andWhere(['cartStatus'=>'Active'])->asArray()->one();
    //         if(empty($checkcart)){
    //             if($this->createCart($userid,$productid,$quantity)){
    //                 return json_encode('true');
    //             }

    //         }else {
    //             $this->createCartItems($checkcart['cartId'],$productid,$quantity);
    //         }

    //     }

    // public function createCart($userid,$productid,$quantity){
    //     $model = New Productcart();
    //     $data = ['Productcart'=>['userId'=>$userid,'total'=>0,'cartStatus'=>'Active','createdBy'=>yii::$app->user->id]];
    //     if($model->load($data) && $model->save()){
    //         $this->createCartItems($model->cartId,$productid,$quantity);
    //     }
    //     return false;
    // }


}
